# Generated by Django 5.1 on 2024-08-30 06:51

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0003_bookingdb_booking_date_bookingdb_movie_and_more"),
        ("movies", "0001_initial"),
        ("theatres", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movieschedule",
            name="available_seats",
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
        migrations.AddField(
            model_name="movieschedule",
            name="theatre",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="theatres.movietheatre",
            ),
        ),
        migrations.AddField(
            model_name="viewhistory",
            name="booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bookings.bookingdb",
            ),
        ),
        migrations.AddField(
            model_name="viewhistory",
            name="movie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="movies.moviemodel",
            ),
        ),
        migrations.AddField(
            model_name="viewhistory",
            name="user_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="moviemodel",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="moviemodel",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="moviemodel",
            name="director",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="moviemodel",
            name="duration",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="moviemodel",
            name="genre",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="moviemodel",
            name="rating",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=3, null=True
            ),
        ),
        migrations.AlterField(
            model_name="moviemodel",
            name="release_date",
            field=models.DateField(
                blank=True, default=datetime.datetime.now, null=True
            ),
        ),
        migrations.AlterField(
            model_name="moviemodel",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="movieschedule",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="movieschedule",
            name="movie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="movies.moviemodel",
            ),
        ),
        migrations.AlterField(
            model_name="movieschedule",
            name="show_time",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime.now, null=True
            ),
        ),
        migrations.AlterField(
            model_name="movieschedule",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="viewhistory",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="viewhistory",
            name="last_viewed",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="viewhistory",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
