# Generated by Django 4.2.13 on 2024-08-18 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theatres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheatreSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_row', models.CharField(max_length=1)),
                ('number_of_seats', models.PositiveIntegerField()),
                ('row_range', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('theatre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theatres.movietheatre')),
            ],
        ),
    ]
